### ISSUE TITLE
cleanup onrange parametrisation

### ISSUE THREAD

**Issue by neutrinoceros** [volodia99/nonos#16]
small_com : note pour une amélioration future possible. Que dirais-tu si au lieu d'avoir ces modes, on fasse quelque chose comme :
nonos -> ne fait rien (ou alors show un -on par défaut)
nonos -on 10 -> show le 10eme .vtk
nonos -on 10 -png/-pdf -> save le 10eme .vtk au bon format
nonos -on (0,6,2) -png -> save les .vtk 0,2,4,6 en png (on utiliserait en une fois -onStart, -onEnd et -onStep. C'est peut-être une idée bif-bof ou pas facilement réalisable je sais pas. Pourrait peut-être du coup régler le probleme de redondance dans les 2 modes)

_Originally posted by @volodia99 in https://github.com/volodia99/nonos/pull/12#discussion_r614251398_

**Comment by neutrinoceros** [comment]
a possible implementation
```
import argparse
import sys

def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("-on", nargs="+", default=[1], type=int)
    args = parser.parse_args()

    if len(args.on) > 3:
        return 1
    if len(args.on) == 1:
        onrange = args.on
    else:
        args.on[1] += 1
        onrange = range(*args.on)

    print(onrange)
    print(list(onrange))

if __name__ == "__main__":
    sys.exit(main())
```

**Comment by volodia99** [comment]
Be careful about two things :
* how to create a full movie in command line ? (`nonos -on 0 -1 -img png` ? ) Or maybe `nonos -all -img png` which would make an image from all .vtk files in the datadir.
* how does this new mode could work with a local config file, if we replace `-onEnd`, `-onStep` and `-mod` ?

**Comment by neutrinoceros** [comment]
I'm trying to think about your first question, it's not obvious to me what's the best solution here yet.
Now about the configuration file, it should work pretty much as on the command line, but I'm not sure how.

I'm in the process of simplifying the "film mode" code block so that it can later be merged back with the "display mode" one, but I think that we need to think it thoroughly before fusing them.
