### ISSUE TITLE
bug: -diff flag is broken in 'film' mode

### ISSUE THREAD

**Issue by neutrinoceros** [volodia99/nonos#19]
automatic computation of vmin and vmax is currently broken, as we don't have a unified mechanism to compute them in every use-case;
I think it'll be tremendously easier to work on a stable solution for this after #17 in completed.

**Comment by volodia99** [comment]
Note : initially, 4 cases in film mode :
* -diff --> vmin/vmax were specified in the default config
* -diff -vmin=xxx -vmax=xxx -->  vmin/vmax were specified in command line
* --> vmin/vmax were automatically computed given an arbitrary output
* -vmin=xxx -vmax=xxx -->  vmin/vmax were specified in command line

Possibility : vmin/vmax "unset" in the default config. if diff, we calculate vmin, and we say vmax=-vmin. if not, we compute automatically given an arbitrary output.

**Comment by neutrinoceros** [comment]
fixed by #30
